<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
class LaptopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('devicemodels')->insert([
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '1',
               'eq_number' => '01-68-7440-001-0002-00001',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  //add
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', //add
               'contract_no' => 'ซ.1/2568',      //add
               'contract_date' => '2025-02-17',  //add            
               'warranty_start' =>'2025-06-02',  //add
               'warranty_end' => '2026-06-01',   //add
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '2',
               'eq_number' => '01-68-7440-001-0002-00002',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '3',
               'eq_number' => '01-68-7440-001-0002-00003',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '4',
               'eq_number' => '01-68-7440-001-0002-00004',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '5',
               'eq_number' => '01-68-7440-001-0002-00005',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '6',
               'eq_number' => '01-68-7440-001-0002-00006',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '7',
               'eq_number' => '01-68-7440-001-0002-00007',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '8',
               'eq_number' => '01-68-7440-001-0002-00008',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '9',
               'eq_number' => '01-68-7440-001-0002-00009',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '10',
               'eq_number' => '01-68-7440-001-0002-00010',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '11',
               'eq_number' => '01-68-7440-001-0002-00011',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '12',
               'eq_number' => '01-68-7440-001-0002-00012',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '13',
               'eq_number' => '01-68-7440-001-0002-00013',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '14',
               'eq_number' => '01-68-7440-001-0002-00014',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '15',
               'eq_number' => '01-68-7440-001-0002-00015',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '16',
               'eq_number' => '01-68-7440-001-0002-00016',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '17',
               'eq_number' => '01-68-7440-001-0002-00017',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '18',
               'eq_number' => '01-68-7440-001-0002-00018',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'model' => '240-G10',
               'eq_no' => '19',
               'eq_number' => '01-68-7440-001-0002-00019',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'modeles' => '240-G10',
               'eq_no' => '20',
               'eq_number' => '01-68-7440-001-0002-00020',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'modeles' => '240-G10',
               'eq_no' => '21',
               'eq_number' => '01-68-7440-001-0002-00021',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'modeles' => '240-G10',
               'eq_no' => '22',
               'eq_number' => '01-68-7440-001-0002-00022',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'modeles' => '240-G10',
               'eq_no' => '23',
               'eq_number' => '01-68-7440-001-0002-00023',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
            [
               'type' => 'อุปกรณ์ทำงานสารสนเทศ',
               'type_eq' => 'Notebook',
               'brand' => 'HP',
               'modeles' => '240-G10',
               'eq_no' => '24',
               'eq_number' => '01-68-7440-001-0002-00024',
               'eq_number_it' => '-',
               'service_life' => '2568',
               'os' => 'Windows 11',
               'accessories' => null,
               'path_img' => null,
               'service_provider' => 'บริษัท อินฟอร์เมชั่น เซอร์วิส แอนด์ คอนซัลแทนท์ จำกัด (ISC)',  
               'contract' => 'สัญญาซื้อขายครุภัณฑ์คอมพิวเตอร์ จำนวน 13 รายการ ประจำปีงบประมาณ พ.ศ.2568', 
               'contract_no' => 'ซ.1/2568',      
               'contract_date' => '2025-02-17',              
               'warranty_start' =>'2025-06-02',  
               'warranty_end' => '2026-06-01',   
               'status' => '1',
               'deleted' => '0',
               'created_at' => now(),
               'updated_at' => now(),               
            ],
        ]);
    }
}
