<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
class UsersSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'email' => 'angsumaporn.t@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อังศุมาพร',
                'surname' => 'เทียมเพ็ชร์',
                'affiliation' => 'กองมาตรฐานอาคารสถานกีฬา',
                'job_group' => 'กลุ่มมาตรฐานอาคารสถานกีฬา',
                'job_position' => '-',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
             [
                'email' => 'kanphatson.k@dpe.go.th',    
                'prefix' => '-',
                'name' => 'Kanphatson',
                'surname' => 'Kerdkaew',
                'affiliation' => '-',
                'job_group' => '-',
                'job_position' => '-',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'atcharat.y@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อัชรัฐ',
                'surname' => 'ยงทวี',
                'affiliation' => 'สำนักวิทยาศาสตร์การกีฬา',
                'job_group' => 'กลุ่มวิจัยและพัฒนา',
                'job_position' => 'ผู้อำนวยการกลุ่มพัฒนาเทคโนโลยีทางการกีฬา',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'anchalaphorn.b@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อัญชลาภรณ์',
                'surname' => 'บัวทอง',
                'affiliation' => 'สถาบันพัฒนาบุคลากรพลศึกษาและการกีฬา',
                'job_group' => 'กลุ่มบริหารงานทั่วไป',
                'job_position' => 'ผู้อำนวยการกลุ่มบริหารงานทั่วไป',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'unchalee.s@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อัญชลี',
                'surname' => 'สุขเรือน',
                'affiliation' => 'กองยุทธศาสตร์และแผนงาน',
                'job_group' => 'กลุ่มบริหารงานทั่วไป',
                'job_position' => 'นักวิเคราะห์นโยบายและแผน',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'atittaya.i@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อาทิตยา',
                'surname' => 'อินทร์แก้ว',
                'affiliation' => 'สำนักนันทนาการ',
                'job_group' => 'กลุ่มวิจัยและพัฒนา',
                'job_position' => 'นักพัฒนาการกีฬา',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'nattakan.s@dpe.go.th',    
                'prefix' => '-',
                'name' => 'ณัฐกานต์',
                'surname' => 'สานนท์',
                'affiliation' => 'สำนักเลขนานุการกรม',
                'job_group' => 'กลุ่มพัสดุ',
                'job_position' => '-',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'arthorn.k@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อาธร',
                'surname' => 'กองไตร',
                'affiliation' => '-',
                'job_group' => 'กลุ่มพัฒนาผู้ตัดสินกีฬา',
                'job_position' => 'นักพัฒนาการกีฬาปฏิบัติการ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'arnop.s@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อานพ',
                'surname' => 'ศรีสุข',
                'affiliation' => 'กองมาตรฐานอาคารสถานการกีฬา',
                'job_group' => 'กลุ่มบริหารงานทั่วไป',
                'job_position' => 'นักจัดการงานทั่วไป',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'patcharaporn.l@dpe.go.th',    
                'prefix' => '-',
                'name' => 'พัชราภรณ์',
                'surname' => 'โลกคำลือ',
                'affiliation' => 'สำนักเลขนานุการกรม',
                'job_group' => 'กลุ่มการคลัง',
                'job_position' => 'เจ้าพนักงานการเงินและบัญชีปฏิบัติงาน',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'pimchanok.p@dpe.go.th',    
                'prefix' => '-',
                'name' => 'พิมพ์ชนก',
                'surname' => 'ภัทรนภาวัน',
                'affiliation' => 'สำนักเลขนานุการกรม',
                'job_group' => 'กลุ่มการคลัง',
                'job_position' => 'เจ้าหน้าที่การเงินและบัญชี',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'suthon.w@dpe.go.th',    
                'prefix' => '-',
                'name' => 'สุธน',
                'surname' => 'วิชัยรัตน์',
                'affiliation' => 'สถาบันพัฒนาบุคลากรพลศึกษาและการกีฬา',
                'job_group' => '-',
                'job_position' => 'ผู้อำนวยการสถาบันพัฒนาบุคลากรการพลศึกษาและการกีฬา',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'anuwat.c@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อนุวัฒน์',
                'surname' => 'ไชยเรศ',
                'affiliation' => 'กองมาตรฐานอาคารสถานกีฬา',
                'job_group' => 'กลุ่มมาตรฐานอาคารสถานกีฬา',
                'job_position' => 'นายช่างไฟฟ้าชำนาญงาน',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'apirom.a@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อภิรมย์',
                'surname' => 'อาทิตย์ตั้ง',
                'affiliation' => 'สำนักวิทยาศาสตร์การกีฬา',
                'job_group' => 'วิทยาศาสตร์สุขภาพ',
                'job_position' => 'นักพัฒนาการกีฬาปฏิบัติการ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'apirat.r@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อภิรัฐ',
                'surname' => 'รัตนวงค์',
                'affiliation' => 'สำนักเลขนานุการกรม',
                'job_group' => 'กลุ่มพัสดุ',
                'job_position' => '-',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'oratai.l@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อรทัย',
                'surname' => 'เลิช',
                'affiliation' => 'สำนักนันทนาการ',
                'job_group' => 'กลุ่มบริหารงานทั่วไป',
                'job_position' => 'นักพัฒนาการกีฬาชำนาญการพิเศษ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'arkapong.m@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อรรคพงษ์',
                'surname' => 'ไมตรีจิตต์',
                'affiliation' => '-',
                'job_group' => 'กลุ่มกีฬาส่วนภูมิภาค',
                'job_position' => 'นักพัฒนาการกีฬาชำนาญการพิเศษ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'attachai.c@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อรรถชัย',
                'surname' => 'ไชยวัต',
                'affiliation' => '-',
                'job_group' => 'กลุ่มอนุรักษ์ศิลปะมวยไทยและกีฬาไทย',
                'job_position' => 'นักพัฒนาการกีฬาปฏิบัติการ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],           
            [
                'email' => 'orawan.y@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อรวรรณ',
                'surname' => 'เยี่ยมรัมย์',
                'affiliation' => '-',
                'job_group' => 'กลุ่มบริหารงานทั่วไป',
                'job_position' => 'นักพัฒนาการกีฬาปฏิบัติการ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'arinchai.m@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อริญชัย',
                'surname' => 'ไม้เนื้อทอง',
                'affiliation' => 'สำนักเลขนานุการกรม',
                'job_group' => 'กลุ่มประชาสัมพันธ์',
                'job_position' => 'เจ้าหน้าที่ประชาสัมพันธ์ด้านบริการประชาชน',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'aroon.s@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อรุณ',
                'surname' => 'สุรเชิดเกียรติ',
                'affiliation' => 'สำนักเลขนานุการกรม',
                'job_group' => 'กลุ่มประชาสัมพันธ์',
                'job_position' => '-',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'arunnee.a@dpe.go.th',    
                'prefix' => '-',
                'name' => 'อรุณนีย์',
                'surname' => 'เอื้อเฟือสุข',
                'affiliation' => '-',
                'job_group' => '-',
                'job_position' => '-',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'supaporn.s@dpe.go.th',    
                'prefix' => '-',
                'name' => 'สุภาพร',
                'surname' => 'ทรัพย์โสม',
                'affiliation' => 'สำนักนันทนาการ',
                'job_group' => '-',
                'job_position' => 'เจ้าพนักงานธุรการชำนาญงาน',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
            [
                'email' => 'supasinee.j@dpe.go.th',    
                'prefix' => '-',
                'name' => 'สุภาสินี',
                'surname' => 'จันทรนิกูล',
                'affiliation' => 'สำนักงานเลขนานุการกรม',
                'job_group' => 'กลุ่มช่วยอำนวยการและสารบรรณ',
                'job_position' => 'นักจัดการงานทั่วไปปฏิบัติการ',           
                'phone' => '-',
                'email_verified_at' => null,
                'password' => Hash::make('Dpe@2025'), // password
                'view_pass' => 'Dpe@2025',
                'remember_token' => null,
                'role' => '0',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => '1',
            ],
        ]);
    }
}
